### ISSUE TITLE
Perform transform in-memory, not on-disk

### ISSUE THREAD

**Issue by azz** [azz/prettier-tslint#1]
Requires https://github.com/palantir/tslint/issues/1760

**Comment by azz** [comment]
Upstream PR: https://github.com/palantir/tslint/pull/3371

**Comment by peteyy** [comment]
It's been quite a while now. Would it be possible to use a fork instead? @azz

**Comment by azz** [comment]
Won't be using a fork but I'll probably have to implement some more logic in the repo that I originally planned.

**Comment by RWOverdijk** [comment]
👍  once this is in and behaviour is the same as prettier-eslint I can implement it as a step in boards.
