### ISSUE TITLE
VSCode integration

### ISSUE THREAD

**Issue by romainquellec** [azz/prettier-tslint#11]
Hello.

I wanted to used a simple thing to get prettier and tslint working together (this project so :D) with VsCode, on save.

Is there any steps I'm missing ?

**Comment by romainquellec** [comment]
Oh, ok. It's blocked by #1.
So, to be sure: It's not possible, right now, is VsCode, right ?

**Comment by orblazer** [comment]
Hello, i have make an PR for that here and on `prettier-vscode` (https://github.com/prettier/prettier-vscode/pull/414)
