### ISSUE TITLE
[prettier-vscode] max-line-length does not work

### ISSUE THREAD

**Issue by sveyret** [azz/prettier-tslint#15]
When setting tslintIntegration to true, prettier does not take into account its print-width rule anymore, neither it takes the max-line-length rule from tslint for formatting line length. When formatting files, it acts as if the print-width would be 80.

Here is my configuration:

VS config (extract):
```Typescript
    "prettier.tslintIntegration": true,
```

tslint.yaml (extract):
```yaml
extends:
  - >-
    common/tslint
```

common/tslint.yaml (extract):
```yaml
  max-line-length:
    options:
      limit: 120
```

**Comment by rambabusaravanan** [comment]
Yes, not working 😒 

prettier has`"prettier.printWidth": 120` in vscode settings.json 
tslint has `"max-line-length": [true, 120]` in tslint.json

The line breaks is not working when `"prettier.tslintIntegration": true`
When false, it is working as per the `prettier.printWidth`. But when true, it is considering nether `prettier.printWidth` nor `max-line-length` from tslint

vscode settings.json
```json
{
  "editor.formatOnSave": true,
  "editor.tabSize": 2,
  "eslint.autoFixOnSave": true,
  "eslint.packageManager": "yarn",
  "git.autofetch": true,
  "npm.packageManager": "yarn",
  "prettier.eslintIntegration": true,
  "prettier.printWidth": 120,
  "prettier.tslintIntegration": true,
  "tslint.autoFixOnSave": true,
  "tslint.packageManager": "yarn"
}

```

DIsclaimer: I have prettier, eslint and tslint plugins installed in VSCode but nothing installed as dependency via package.json

**Comment by rambabusaravanan** [comment]
I think labeling this as "_Bug_" would be more appropriate than "_Enhancement_" as enabling `tslintIntegration` is not accepting tslint `max-line-length` but breaks existing settings `prettier.printWidth` instead

**Comment by aleclarson** [comment]
You _cannot_ use tslint's `max-line-length` **only**. Prettier will run with its default setting of `maxWidth: 80` if you never override it explicitly in your `.prettierrc` or similar file.

If the opposite (ie: using Prettier's `maxWidth` only) is not working as expected, try setting tslint's `max-line-length` to `false`.

If it's still not working, please provide a repository with a minimum reproduction of the issue.

**Comment by james2406** [comment]
Thanks @aleclarson! For now, creating a `. prettierrc ` file with the following configuration is a good workaround:

```json
{
  "printWidth": 120
}
```

**Comment by aleclarson** [comment]
@james2406 You can keep `max-line-length`, but it's a no-op.

**Comment by aleclarson** [comment]
Tracking this in #25

**Comment by rambabusaravanan** [comment]
@aleclarson In case I create `.prettierrc` as a workaround, max line length works well.
But creating .prettierrc, immediately breaks other tslint rules like single quote fails in .js files (works fine in .ts file).
Note: this quote rule worked fine for .js and .ts files when no `.prettierrc`

.prettierrc (before)
```
{
  "printWidth": 120,
  "trailingComma": "es5"
}
```

failing tslint rule for .js files (works in .ts file)
```
  "rules": {
    "quotemark": [true, "single", "jsx-double"]
  },
```

.prettierrc (workaround now)
```
{
  "printWidth": 120,
  "trailingComma": "es5",
  "singleQuote": true
}
```

please help us with consistency across prettier and tslint

**Comment by aleclarson** [comment]
@rambabusaravanan Please open a new issue with the features you'd like to see added. Thanks! 👍
