### ISSUE TITLE
[prettier-vscode] semicolon does not work

### ISSUE THREAD

**Issue by sveyret** [azz/prettier-tslint#16]
When setting tslintIntegration to true, prettier does not take into account its semi rule anymore, neither it takes the semicolon rule from tslint, at least in interface definition.

For example, in my interface definition:
```Typescript
export interface ApiDefinition extends RoutesType {
  lang: {
    url: { langCode: string }
    data: undefined
    header: undefined
    return: void
  }
  securityToken: {
    url: undefined
    data: undefined
    header: undefined
    return: string
  }
}
```
code formatting adds semicolons at almost each line:
```Typescript
export interface ApiDefinition extends RoutesType {
  lang: {
    url: { langCode: string };
    data: undefined;
    header: undefined;
    return: void;
  }
  securityToken: {
    url: undefined;
    data: undefined;
    header: undefined;
    return: string;
  }
}
```

Here is my configuration:

VS config (extract):
```Typescript
    "prettier.tslintIntegration": true,
```
tslint.yaml (extract):
```Yaml
extends:
  - >-
    common/tslint
```
common/tslint.yaml (extract):
```Yaml
  semicolon:
    options:
      - never
```

**Comment by aleclarson** [comment]
You have no `.prettierrc` or similar file? Please provide a repository with a simple example of the issue.

**Comment by aleclarson** [comment]
Closing until a minimal repro is provided. You can [fork this repository](https://github.com/aleclarson/repro/tree/prettier-tslint-19) as a starting point.

**Comment by sveyret** [comment]
Hello @aleclarson,
I have no .prettierrc or any similar file. I created a minimal repo from yours as your suggested. You can find it [here](https://github.com/sveyret/repro/tree/prettier-tslint-16), but I must say that there is nothing more than what is described in the first message.

**Comment by sveyret** [comment]
Not sure I can re-open the issue myself. If so, please explain me how. If not, I will let you do it…
Thanks.

**Comment by sveyret** [comment]
Deleting my minimal repo as no answer to this issue.
