### ISSUE TITLE
What exactly this combo does that prettier can't?

### ISSUE THREAD

**Issue by ackvf** [azz/prettier-tslint#29]
I am quite confused by all the different npm packages and the various approaches to set up a project properly.

I wonder what benefits using prettier+prettier-tslint bring and how does it compare to [tslint-config-prettier](https://www.npmjs.com/package/tslint-config-prettier) ?

**Comment by azz** [comment]
The only reason you'd want this package is if you want custom formatting rules from tslint to take precedence over Prettier. If you're happy with Prettier's formatting you should use [tslint-plugin-prettier](https://github.com/prettier/tslint-plugin-prettier).
