### ISSUE TITLE
Accept array of files

### ISSUE THREAD

**Issue by KurtPreston** [azz/prettier-tslint#8]
Currently, if you want to lint / prettify files, you need to do them one at a time.  When processing multiple files, I suspect it would probably execute much quicker if the `fix` and `check` methods accepted an array of files, so prettier and tslint could process them in bulk.

**Comment by azz** [comment]
Thanks for the suggestion! For the moment there would be no perf benefits from doing this as config has to be looked up on a per-file basis. So `files.map(check)` should be ok. If there are perf reasons introduced that ask for this we can reconsider.
