### ISSUE TITLE
tslint as peer depenendcy

### ISSUE THREAD

**Issue by zimme** [azz/prettier-tslint#9]
Shouldn't tslint be a peer dependency as well?

**Comment by azz** [comment]
I was hoping to get https://github.com/palantir/tslint/pull/3371 merged into tslint, which would put a hard version requirement on this package, so wanted that flexibility. If that falls through we can definitely consider making it a peer dep.

Was there any specific issue having it as a peer dep would solve though?

**Comment by zimme** [comment]
For now there's no problem, but we're having the same discussion in https://github.com/prettier/prettier-eslint/issues/133.

I'm just thinking that it might make the versioning of `prettier` and `(e|t)slint` easier if they are peer dependencies.

But now that I'm writing it down maybe this isn't a dependency vs peer dependency problem, but a dependency version problem and making sure we have the correct dependency version specified?

**Comment by zimme** [comment]
Give users `prettier` and `(e|t)slint` automatically at the latest supported version
vs
Have users bring their own `prettier` and `(e|t)slint` within the allowed scope.

**Comment by azz** [comment]
I don't think I've seen a project with three peer deps before :wink:

**Comment by aleclarson** [comment]
https://github.com/prettier/prettier-eslint/issues/133 has since been closed, so I'm closing this too.
